### ISSUE TITLE
move build logic to cargo subcommand

### ISSUE THREAD

**Issue by goertzenator** [goertzenator/rust.mk#3]
Move all the logic from `rust.mk` into a [cargo subcommand](https://github.com/rust-lang/cargo/wiki/Third-party-cargo-subcommands).  The command would be installed with..

```
cargo install cargo-erlangapp
```

... and run with ...

```
cargo erlangapp [build|test|clean|distclean]
```

`erlang.mk` and `rebar3` plugins could then be built as thin wrappers around `cargo-erlangapp`.

Assumptions and motivators:
- `rust.mk` is eventually going to need a JSON parser to deal with multi-target crates.  This is an awkward requirement for a Makefile, but easily achieved by a rust crate.
- `cargo-erlangapp` can be easily and reliably built on common Rust and Erlang target platforms.
- Consistent handling of Rust code from different Erlang build systems will be good for the user.

**Comment by goertzenator** [comment]
This subcommand is now [implemented](https://github.com/goertzenator/cargo-erlangapp), and rust.mk has a [branch](https://github.com/goertzenator/rust.mk/tree/cargoerlangapp) to use it.

@nlfiedler, could I convince you to test the above `cargoerlangapp` branch on OSX?

**Comment by nlfiedler** [comment]
I don't know anything about erlang.mk, so I'm just guessing at how to test this. I cloned this repository, changed to the demo directory, and typed `make` and got what appeared to be a successful build. The `priv` directory contained the rust binaries, which is what I would expect. Does that sound about right, or should I run some other commands as well?

**Comment by goertzenator** [comment]
Also do a `make test` (or is it `make tests`?), but it sounds like it is going to work based on what you've already said, so thanks!

I'll merge this branch to master, and then the stage is set for a simple rebar3 plugin using cargo-erlangapp.  Thanks for helping the Rust-Erlang ecosystem move along!

**Comment by nlfiedler** [comment]
`All 5 tests passed.`  :)

**Comment by nlfiedler** [comment]
Sorry!!

I failed to do the most important thing, and checkout the branch. It fails to build:

```
/Users/nfiedler/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-erlangapp-0.1.1/src/lib.rs:135:9: 135:25 error: mismatched types [E0308]
/Users/nfiedler/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-erlangapp-0.1.1/src/lib.rs:135         Target::Dylib(_) =>
                                                                                                             ^~~~~~~~~~~~~~~~
/Users/nfiedler/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-erlangapp-0.1.1/src/lib.rs:135:9: 135:25 help: run `rustc --explain E0308` to see a detailed explanation
/Users/nfiedler/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-erlangapp-0.1.1/src/lib.rs:135:9: 135:25 note: expected type `&Target`
/Users/nfiedler/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-erlangapp-0.1.1/src/lib.rs:135:9: 135:25 note:    found type `Target`
error: aborting due to previous error
error: failed to compile `cargo-erlangapp v0.1.1`, intermediate artifacts can be found at `/var/folders/fr/lvzcyq6931q0b3yvsw12kq9h0000gn/T/cargo-install.3QDjhMVcIzQL`
```

**Comment by nlfiedler** [comment]
Here's the diff I used to get the cargo erlang-app subcommand to build:

```
diff --git a/src/lib.rs b/src/lib.rs
index e7c828a..5841128 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -16,6 +16,8 @@ macro_rules! otry(
     ($e:expr) => (match $e { Some(e) => e, None => return None })
 );

+static LINKER_ARGS: &'static[&'static str] = &["--", "--codegen", "link-args='-flat_namespace -undefined suppress'"];
+
 /// Simple text error type for this application
 #[derive(Debug)]
 struct MsgError {
@@ -131,9 +133,9 @@ fn build_crates(argsinfo: &ArgsInfo, appdir: &Path) -> Result<(), MsgError> {
 // Without them linker throws a fit about NIF API calls.
 #[cfg(target_os="macos")]
 fn linker_args(target: &Target) -> &'static [&'static str] {
-    match target {
+    match *target {
         Target::Dylib(_) =>
-            &["--", "--codegen", "link-args='-flat_namespace -undefined suppress'"],
+            LINKER_ARGS,
         _ =>
             &[],
     }
```

There's probably a smoother way, but my Rust skills are not strong.

**Comment by nlfiedler** [comment]
Needed another edit to cargo-erlangapp as well:

```
@@ -94,7 +96,7 @@ fn build_crates(argsinfo: &ArgsInfo, appdir: &Path) -> Result<(), MsgError> {
             rustc_args.extend(linker_args(&target).iter().map(|x|x.to_string()));

             // build it!
-            try!(cargo_command("rustc", argsinfo.cargo_args.as_slice(), crate_dir));
+            try!(cargo_command("rustc", rustc_args.as_slice(), crate_dir));

             // copy artifacts to priv/crates/<cratename>
             let (dst_name, src_name) = target_filenames(&target);
```

However, the tests fail because the `link-args` are escaped: `link-args=\'-flat_namespace\ -undefined\ suppress\'` which confuses `rustc` and I get `note: clang: error: no such file or directory: ''-flat_namespace'` at the end. No idea where the escaping is happening.

I'll continue to look at this tomorrow, as I'm out of time tonight.

**Comment by goertzenator** [comment]
Thanks for all your work.  I'll dig into this now by adding some link args to a linux build.

**Comment by goertzenator** [comment]
It looks like bash strips the single quotes from the args when run from a Makefile, but that won't happen when launching a process from Rust.  Does it work if you change `"link-args='-flat_namespace -undefined suppress'"` to `"link-args=-flat_namespace -undefined suppress"`.

And thanks for pointing out the `argsinfo/rustc_args` bug, that was a bad one.  I though I was decent at Rust, but writing this program has been humbling...

**Comment by nlfiedler** [comment]
My intuition said "no", but trying proved to work. I tested by patching cargo-erlangapp and using `cargo install --root=...` to get the subcommand installed into the rust.mk test directory, and then `make && make tests` on the `cargoerlangapp` branch. Everything compiles cleanly and the tests pass. You are good to go.

BTW, the spaces get escaped (by something): `link-args=-flat_namespace\ -undefined\ suppress`. That explains why the arguments get through to rustc without the need for the quotes.

**Comment by goertzenator** [comment]
Excellent!  I'll publish a fixed version soon.

Out of curiosity, where are you seeing the space escaped string?  My understanding is that there should be no escaping in parameters to process::Command.  They are passed verbatim like strings to a function.

**Comment by nlfiedler** [comment]
Yeah, the escaping was a curiosity. I also came to the conclusion that `process::Command` was not doing the escaping. I'm seeing the escaping in the build output, in bash. Maybe cargo is escaping the commands when printing to the screen?

**Comment by goertzenator** [comment]
I think you were seeing some debug output that I've since removed.

Anyway, this branch is now merged to master.  Thanks again for all your help!
